### ISSUE TITLE
Create "Movement" Node

### ISSUE THREAD

**Issue by reoliveira** [ubc-subbots/Jormungandr#10]

**Comment by reoliveira** [comment]
Simply create a basic node for movement and add it to the system.

All it should do as of this ticket is exist and set up its subscribers and publishers and have a data flow skeleton

**Comment by garethellis0** [comment]
What would this node be publishing and subscribing to? Would that be the `Motor Control` node in this diagram? https://docs.google.com/drawings/d/1MaPxJWud5bFzmcEXeeSdvQhpYj6Fnxo1-z62Ig3mTH4/edit

**Comment by garethellis0** [comment]
This node would be subscribing to a `geometry_msgs/Twist` message, and outputting PWM signals over serial to the controller. 

From @Dulluhan: timeline for this is about one month - roughly mid february

**Comment by Dulluhan** [comment]
First step would be to develop a math model for the plant before a controller can be designed. It would be great if I could take a look at @newtoncn's matlab model. Will be looking into multidimensional control systems as well as starting a rough hardware interaction node.

**Comment by Dulluhan** [comment]
It is possible to abstract things for now and develop the communication portions of the node. I will start looking at this.
