### ISSUE TITLE
Create "Decision Maker" Node

### ISSUE THREAD

**Issue by reoliveira** [ubc-subbots/Jormungandr#12]

**Comment by reoliveira** [comment]
Simply create a basic node for decision making and add it to the system. This is the Decision Maker as seen in the design for it ![here](https://docs.google.com/drawings/d/1MaPxJWud5bFzmcEXeeSdvQhpYj6Fnxo1-z62Ig3mTH4/edit) 

All it should do as of this ticket is exist and set up its subscribers and publishers and have a skeleton of the state machine and how that should be set up. Consider that we will possibly need multiple state machines, one for the qualifying and one for the actual run and how we want to put that in the design.

**Comment by garethellis0** [comment]
Just a note, the link in the above comment appears to be broken, I get `Non-Image content-type returned` when I try to visit it.
