### ISSUE TITLE
Create the "World State" Node

### ISSUE THREAD

**Issue by garethellis0** [ubc-subbots/Jormungandr#26]
This node should:
- On a state change (for example, after we move through the first gate and see the line on the bottom of the pool), send out a `StateChange` message (to be created) indicating what the new state is

**TODO**
- Create a `StateChange` ROS message that contains our current state (chosen from a discrete set of options, a enum)
- Figure out what the discrete state should be for the first part of the course
- For every discrete state, find some indicators based on IMU, Sonar Pingers, Cameras so that we know when to trigger the state change.

**Note: This is a 'shell' class, with no current state/boundary definitions**

**Comment by Dulluhan** [comment]
Not sure if this is the same or overlapping with #31.

**Comment by garethellis0** [comment]
I think the idea was that this would make use of #31 to help make a decision about the state of the robot in the course (ie. what task we are currently working on)

**Comment by Dulluhan** [comment]
Ok, just wanted to see if opening #31 was valid
