### ISSUE TITLE
Decide on Camera

### ISSUE THREAD

**Issue by reoliveira** [ubc-subbots/Jormungandr#3]

**Comment by reoliveira** [comment]
The decision has been made to use a two camera setup, one facing forward and one facing downward.

A camera needs to be decided on, consider the needs of the team and scope out a camera to use. Preferably one that has existing ROS support, as found on http://wiki.ros.org/Sensors#Cameras

**Comment by garethellis0** [comment]
One possible option: https://www.amazon.ca/ELP-180degree-Fisheye-windows-android/dp/B00LQ854AG
