### ISSUE TITLE
Find and Add Package for Camera

### ISSUE THREAD

**Issue by reoliveira** [ubc-subbots/Jormungandr#4]

**Comment by reoliveira** [comment]
Once a camera has been decided on, we need a "driver" to be able to communicate with it and receive data. If there already is a default ROS package for the picked camera, get that one. Otherwise issues will need to be created to build on ourself.

- Get/Create a package that will receive data from the camera and integrate it into our system
- Test the package

**Comment by garethellis0** [comment]
Snowbots has a node that should be usable with any USB webcam: https://github.com/UBC-Snowbots/Snowflake/blob/core/src/vision/src/camera_init.cpp
