### ISSUE TITLE
Need assertions on command line parameters for init_test_case.sh

### ISSUE THREAD

**Issue by owenguo-UBC** [ubc-subbots/Jormungandr#70]

**Comment by garethellis0** [comment]
Heya, just your friendly neighborhood computer scientist dropping by. This issue should probably get some elaboration. What assertions? Why are they needed? Where is `init_test_case.sh`? 

_answers to these questions and more, later on tonight's program_

**Comment by owenguo-UBC** [comment]
My mistake, I was trying to make this a local issue on my branch but it looks like it works a little differently than I excepted. Good tips though, I will keep those in mind!

**Comment by garethellis0** [comment]
No worries!
